//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_._WEB_ {
    
    
    public partial class LabelPasswordRegexedValidator {
        
        /// <summary>
        /// KeyHidden1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul._web_._CTR_.KeyHidden KeyHidden1;
        
        /// <summary>
        /// label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl label;
        
        /// <summary>
        /// PasswordRegexed1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web._ctr_._WEB_.PasswordRegexed PasswordRegexed1;
        
        /// <summary>
        /// Validator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nilnul.web._ctr_._WEB_.Validator2 Validator1;
    }
}
