//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_._WEB_.ajax.cors.failMsged
{


	public partial class Fill
	{

		/// <summary>
		/// FailMsged control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_._WEB_.ajax.cors.FailMsged1 FailMsged;

		/// <summary>
		/// State control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_._WEB_.State State;

		/// <summary>
		/// OnLoadScript1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul._web_._CTR_.OnLoadScript OnLoadScript1;
	}
}
