//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_._WEB_.map
{


	public partial class Address
	{

		/// <summary>
		/// TxtArea1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_._WEB_.TxtArea1 TxtArea1;

		/// <summary>
		/// Length control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_._WEB_.err.optional_.Length Length;

		/// <summary>
		/// Script__onLoad_Dollar1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul._web_._CTR_.script_.onLoad_.script__onLoad_Dollar Script__onLoad_Dollar1;
	}
}
