//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.web._ctr_._WEB_.txt.err
{


	public partial class Phone
	{

		/// <summary>
		/// Txt4 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_._WEB_.Txt4 Txt4;

		/// <summary>
		/// Regex control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul.web._ctr_._WEB_.err.optional_.Regex Regex;

		/// <summary>
		/// Script__onLoad_Dollar1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::nilnul._web_._CTR_.script_.onLoad_.script__onLoad_Dollar Script__onLoad_Dollar1;
	}
}
